In [1]:
# write a code to check whether a numpy array contains a specified row
import numpy 
arr = numpy.array([[1,4,3,7],
				[2,0,0,2],
				[1,4,3,4],
				[1,4,3,2]])
print(arr)
print([1, 2, 3] in arr.tolist())
print([1,4,3,7] in arr.tolist())
print([3, 2,4, 5] in arr.tolist())
print([2,0,0,3] in arr.tolist())

[[1 4 3 7]
 [2 0 0 2]
 [1 4 3 4]
 [1 4 3 2]]
False
True
False
False


In [3]:
#Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.
import pandas as pd
import numpy as np

exam_data  = {'name': ["Aakarsh","Rishav","jagdev","Aman","chintu"],
        'Math_marks': [98,85,70,75,65],
        'English_marks': [90,80,60,50,65],
        'Result': ["pass","pass","pass","sup.","sup."]}
indexs = [1,2,3,4,5]

df = pd.DataFrame(exam_data , index=indexs)
print(df)

      name  Math_marks  English_marks Result
1  Aakarsh          98             90   pass
2   Rishav          85             80   pass
3   jagdev          70             60   pass
4     Aman          75             50   sup.
5   chintu          65             65   sup.


In [4]:
#write a pandas code to create dataframe from dictionary of narray/list
import pandas as pd
data = {'Students':["Aakarsh","Rishav","Jagdev"],
        'Marks':[95,85,70]}
df = pd.DataFrame(data)
print(df )

  Students  Marks
0  Aakarsh     95
1   Rishav     85
2   Jagdev     70


In [5]:
#write a pandas code to create pandas dataframe using list of lists
import pandas as pd
data = [['Aakarsh', 20], ['Rishav', 19], ['jagdev', 21]]
df = pd.DataFrame(data, columns = ['Name', 'Age'])
print(df )

      Name  Age
0  Aakarsh   20
1   Rishav   19
2   jagdev   21


In [ ]:
#write a code to combine a one and a two dimentional numpy array
import numpy as np
x = np.arange(4)
print("One dimensional array:")
print(x)
y = np.arange(8).reshape(2,4)
print("Two dimensional array:")
print(y)
for a, b in np.nditer([x,y]):
    print("%d:%d" % (a,b),)